define([], function() {
  return {
    "PropertyPaneDescription": "Customize background image, Title text, Description text, a list of button-style links, and the colors of the text and buttons.",
    "BasicGroupName": "Background and Text Settings",
    "LinksPaneDescription": "All settings for the buttons, links, and submenus.",
    "LinksGroupName": "Header Links Configuration",
    "AdditionalInfoDesc": "Additional settings for notifications and custom info.",
    "NotificationsGroupName": "Important Notices Settings",
    "CustomInfoGroupName": "Custom Information Panel 1",
    "CustomInfo2GroupName": "Custom Information Panel 2",
    "BGImgButtonLabel": "Choose Image",
    "BGImgSelectLabel": "Select background image...",
    "GradientColorFieldLabel": "Gradient color",
    "TitleFieldLabel": "Header Title",
    "DescriptionFieldLabel": "Description Section #1",
    "DescriptionPickerLabel": "Section #1 - Audience Target Picker",
    "DescriptionATFieldLabel": "Description Section #2",
    "DescriptionATPickerLabel": "Section #2 - Audience Target Picker",
    "TextColorFieldLabel": "Text color for title and description",
    "BTNColorFieldLabel": "Button color",
    "LinkTxtColorFieldLabel": "Text color for button text",
    "LinksPanelHeader": "Button Links Settings",
    "LinksPanelBtnLabel": "Configure Header Buttons",
    "ConfidentialFieldLabel": "Show Confidential Bar",
    "AnnouncementFieldLabel": "Show announcement",
    "AnnouncementMsgFieldLabel": "Announcement message",
    "AnnouncementMsgFieldHolder": "Enter your announcement here...",
    "AnnouncementTypeFieldLabel": "Type of announcement",
    "AnnouncementLinkToggle": "Include link",
    "AnnouncementLinkLabel": "Link URL",
    "AnnouncementLinkTextPlaceholder": "Link text here...",
    "AnnouncementLinkTextLabel": "Link text",
    "HelpLinkFieldLabel": "Help Link",
    "HelpLinkTextLabel": "Help link text",
    "HelpLinkTextPlaceholder": "Do you need help?",
    "HelpLinkURLLabel": "Help URL",
    "HelpLinkInvertLabel": "Link Color",
    "CustomInfoFieldLabel": "Show section",
    "CustomInfoBGColorLabel": "Custom Info background color",
    "CustomInfoTargetPickerLabel": "Custom Info - Audience Target Picker",
    "PropertyPaneLinksPage": "Configure header links",
    "ButtonLinkTextLabel": "Button text",
    "ButtonLinkUrlLabel": "Link URL"
  }
});