define([], function() {
  return {
    "PropertyPaneDescription": "Customize background image, Title text, Description text, a list of button-style links, and the colors of the text and buttons.",
    "BasicGroupName": "Background and Text Settings",
    "LinksGroupName": "Header Links Configuration",
    "AdditionalGroupName": "Additional Settings",
    "BGImgButtonLabel": "Choose Image",
    "BGImgSelectLabel": "Select background image...",
    "GradientColorFieldLabel": "Gradient color",
    "TitleFieldLabel": "Header Title",
    "DescriptionFieldLabel": "Public Description Field",
    "DescriptionATFieldLabel": "Audience Targetted Description",
    "DescriptionATPickerLabel": "Audience Target Picker",
    "TextColorFieldLabel": "Text color for title and description",
    "BTNColorFieldLabel": "Button color",
    "LinkTxtColorFieldLabel": "Text color for button text",
    "LinksPanelHeader": "Button Links Settings",
    "LinksPanelBtnLabel": "Configure Header Buttons",
    "ConfidentialFieldLabel": "Show Confidential Bar",
    "AnnouncementFieldLabel": "Show announcement",
    "AnnouncementMsgFieldLabel": "Announcement message",
    "AnnouncementMsgFieldHolder": "Enter your announcement here...",
    "AnnouncementTypeFieldLabel": "Type of announcement",
    "AnnouncementLinkToggle": "Include link",
    "AnnouncementLinkLabel": "Link URL",
    "AnnouncementLinkTextPlaceholder": "Link text here...",
    "AnnouncementLinkTextLabel": "Link text",
    "HelpLinkFieldLabel": "Help Link",
    "HelpLinkTextLabel": "Help link text",
    "HelpLinkTextPlaceholder": "Do you need help?",
    "HelpLinkURLLabel": "Help URL",
    "HelpLinkInvertLabel": "Link Color",
    "PropertyPaneLinksPage": "Configure header links",
    "ButtonLinkTextLabel": "Button text",
    "ButtonLinkUrlLabel": "Link URL"
  }
});