import { ITargetAudienceProps } from '../../../common/TargetAudience';
export interface ICloudMarketingHeaderProps extends ITargetAudienceProps {
	// bgimage: string;
	filePickerResult: any;
	gradientcolor: string;
	title: string;
	description: string;
	descriptionat: string;
	titlecolor: string;
	textcolor: string;
	btncolor: string;
	linktxtcolor: string;
	showconfidential: boolean;
	showannouncement: boolean;
	announcementmsg: string;
	announcementtype: string;
	showannouncelink: boolean;
	announcementlink: string;
	announcementlinktext: string;
	showhelplink: boolean;
	helplinktext: string;
	helplinkurl: string;
	helplinkinvert: boolean;
	showcustominfo: boolean;
	custominfocontent: string;
	custominfobgcolor: string;
	audienceTargetsInfo: any[];
	custominfohandler: any;
	showcustominfo2: boolean;
	custominfo2content: string;
	custominfo2bgcolor: string;
	audienceTargetsInfo2: any[];
	custominfo2handler: any;
	context: any;
	pagedisplaymode: boolean;
	audienceTargetsDesc: any[];
	audienceTargetsDescAT: any[];
	headerLinksConfig: any[];
}
